# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: enforce
description: |
  A helm chart for Chainguard's Enforce.
type: application
version: 0.0.1
appVersion: 0.0.1
keywords:
  - chainguard
home: https://chainguard.dev
maintainers:
  - name: The Chainguard Team
    url: https://chainguard.dev
