# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# Invite code assigned to group where clusters will be registered
# This can be retrieved with the following chainctl command:
#   $(chainctl iam invite create $GROUP --cluster -ojson | jq -r .code)
inviteCode:
