# Copyright 2022 Chainguard, Inc.
 # SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: mcp-creds
  namespace: gulfstream
data:
  code: {{ required "\nA valid invite code is required! Ensure you've added your Enforce invite code to the 'inviteCode' in values.yaml.\nIf you need to generate one, you can use:\n\tchainctl iam invite create $GROUP --cluster -ojson | jq -r '.code'\n\nFor more information, see the Chainguard Enforce documentation: https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-user-onboarding/" .Values.inviteCode | b64enc | quote }}

  {{- with .Values.auth.gcp.serviceAccount }}
  {{- if and .key .email }}
  gcp-svc-acct-name: {{ .email | b64enc | quote }}
  gcp-svc-acct-path: {{ "/var/run/sts/gcp.json" | b64enc | quote }}
  gcp.json: {{ .key | quote }}
  {{- end }}
  {{- end }}
