# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gulfstream-rbac
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      gulfstream.dev/controller: "true"
rules: [] # Rules are automatically filled in by the controller manager.

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gulfstream-core
  labels:
    gulfstream.dev/controller: "true"
rules:
  # Allow creating events associated with cluster-scoped resources (e.g. our CRDs)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]

  # Needed to watch and load configuration and secret data.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "watch"]

  # Allow the reconciliation of exactly our validating webhooks.
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "update"]
    resourceNames: ["config.webhook.gulfstream.dev", "validation.webhook.gulfstream.dev"]

  # Allow the reconciliation of exactly our mutating webhooks.
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "update"]
    resourceNames: ["defaulting.webhook.gulfstream.dev"]

  # Allow the reconciliation of exactly our CRDs.
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "update"]
    resourceNames: ["controllers.gulfstream.dev", "webhooks.gulfstream.dev"]

  # These are the resources that we are controlling.
  - apiGroups: ["gulfstream.dev"]
    resources: ["*"]
    verbs: ["get", "list", "update", "watch"]

  # The webhook configured the namespace as the OwnerRef on various cluster-scoped resources,
  # which requires we can Get the system namespace.
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
    resourceNames: ["gulfstream"]
