# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: gulfstream
  labels:
    gulfstream.dev/release: devel
data:
  metrics.backend-destination: prometheus
  metrics.request-metrics-backend-destination: prometheus
