# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-leader-election
  namespace: gulfstream
  labels:
    gulfstream.dev/release: devel
data:
  # This should match the controlplane's replica count.
  buckets: "2"
