# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gulfstream-namespace-rbac
  namespace: gulfstream
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: gulfstream
roleRef:
  kind: Role
  name: gulfstream-namespace-rbac
  apiGroup: rbac.authorization.k8s.io
