# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  labels:
    app: meta-controlplane
  name: webhook
  namespace: gulfstream
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: 8443
  selector:
    app: meta-controlplane
