on:
  workflow_run:
    workflows:
      - Trigger-E2E
    types:
      - completed

jobs:
  e2e:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install yq
        uses: mikefarah/yq@4ee4b09e12ab319a48c6f7eae026030081cb0cc3 # v4.26.1

      - name: Set up Helm
        uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82 # v3.4
        with:
          version: v3.11.2

      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # v2.3.0

      - name: Setup G Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup chainctl
        uses: chainguard-dev/actions/setup-chainctl@main
        with:
          # The Chainguard identity to assume when talking to Enforce.
          identity: ${{ secrets.CHAINCTL_IDENTITY }}

      - run: |
          INVITE_CODE=$(chainctl iam invite create $GROUP --cluster -ojson | jq -r '.code')
          yq -i '.inviteCode = ${INVITE_CODE}' charts/enforce-agent/ci/ci-values.yaml

      - name: Create KIND Cluster
        uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07 # v1.4.0

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
