name: E2E

on:
  workflow_run:
    workflows:
      - Trigger-E2E
    types:
      - completed

jobs:
  e2e:
    runs-on: ubuntu-latest

    permissions:
      statuses: write
      id-token: write
      contents: read

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "E2E Tests"
          description: "Running E2E tests"
          state: 'pending'
          sha: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install yq
        uses: mikefarah/yq@5f4c1fbd0ab1f7c1c97c23deb355a9a4d5077f66 # v4.40.1

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.11.2

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Setup G Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup chainctl
        uses: chainguard-dev/actions/setup-chainctl@main
        with:
          # The Chainguard identity to assume when talking to Enforce.
          identity: ${{ secrets.CHAINCTL_IDENTITY }}

      - run: |
          INVITE_CODE=$(chainctl iam invite create ${{ secrets.CHAINCTL_E2E_GROUP }} --cluster -ojson | jq -r '.code')
          yq -i '.inviteCode = ${INVITE_CODE}' charts/enforce-agent/ci/ci-values.yaml

      - name: Create KIND Cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml

      - name: Run the action # You would run your tests before this using the output to set state/desc
        if: ${{ success() }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "E2E Tests"
          description: "passed!"
          state: 'success'
          sha: ${{ github.event.workflow_run.head_sha }}

      - name: Run the action # You would run your tests before this using the output to set state/desc
        if: ${{ failure() }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "E2E Tests"
          description: "E2E failed!"
          state: 'failure'
          sha: ${{ github.event.workflow_run.head_sha }}
