name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: 3.11.2

      - name: Install sigstore Helm plugin
        run: |
          helm plugin install https://github.com/sigstore/helm-sigstore

      - name: Install GPG Keys
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --import --batch
          gpg --export > /home/runner/.gnupg/pubring.gpg
          gpg --export-secret-keys > /home/runner/.gnupg/secring.gpg

      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SIGN: "true"
          CR_KEY: "${{ secrets.GPG_KEY_NAME }}"
          CR_KEYRING: "/home/runner/.gnupg/secring.gpg"

      - name: Upload Helm Charts to Rekor
        run: |
          for chart in `find .cr-release-packages -name '*.tgz' -print`; do
            helm sigstore upload --keyring=/home/runner/.gnupg/secring.gpg ${chart}
          done

      - name: Push Charts as OCI to GHCR
        run: |
          for chart in `find .cr-release-packages -name '*.tgz' -print`; do
            helm push ${chart} oci://ghcr.io/${GITHUB_REPOSITORY}
          done

